version: "3.7"

services:
  flask:
    build:
      dockerfile: ./docker/Dockerfile_prod
    expose:
      - 8001

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - flask
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      #- ../naturedb-volumes/static:/naturedb-volumes/static
      #- ../naturedb-volumes/admin:/naturedb-volumes/admin
      - ../hikinglend-volumes/bucket:/bucket
      #- ../naturedb-volumes/certbot/conf:/etc/letsencrypt
      #- ../naturedb-volumes/certbot/www:/var/www/certbot
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ../naturedb-volumes/certbot/conf:/etc/letsencrypt
#      - ../naturedb-volumes/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
