"""c

Revision ID: 07eab8a3fcb1
Revises: 876d3be3d581
Create Date: 2023-03-08 06:13:44.262472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eab8a3fcb1'
down_revision = '876d3be3d581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
