"""lonlat2

Revision ID: 0c832ede0da9
Revises: ca4886dddbf5
Create Date: 2023-03-01 22:00:36.456477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c832ede0da9'
down_revision = 'ca4886dddbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
