"""lonlat4

Revision ID: 12415ddbc8cd
Revises: 312b57cf5ca3
Create Date: 2023-03-01 22:20:19.910860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12415ddbc8cd'
down_revision = '312b57cf5ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'longitude_decimal')
    op.drop_column('store', 'latitude_decimal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('latitude_decimal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('store', sa.Column('longitude_decimal', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
