"""lonlat3

Revision ID: 312b57cf5ca3
Revises: 697fca2a3d88
Create Date: 2023-03-01 22:19:54.924663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312b57cf5ca3'
down_revision = '697fca2a3d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
