"""a

Revision ID: 4b83ec2277a7
Revises: 1b5c68cb8bd2
Create Date: 2023-03-08 06:11:41.226531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b83ec2277a7'
down_revision = '1b5c68cb8bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
