"""lonlatx2

Revision ID: 51b7716363a7
Revises: da77bf6a63df
Create Date: 2023-03-01 22:49:26.613692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b7716363a7'
down_revision = 'da77bf6a63df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
