"""x

Revision ID: 57857ca85f7f
Revises: 07eab8a3fcb1
Create Date: 2023-03-08 06:18:13.396159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57857ca85f7f'
down_revision = '07eab8a3fcb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
