"""lonlat del

Revision ID: 614b1428c27b
Revises: 51b7716363a7
Create Date: 2023-03-01 22:49:52.717768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614b1428c27b'
down_revision = '51b7716363a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'longitude_decimal')
    op.drop_column('store', 'latitude_decimal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('latitude_decimal', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.add_column('store', sa.Column('longitude_decimal', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
