"""lonlat3

Revision ID: 697fca2a3d88
Revises: 0c832ede0da9
Create Date: 2023-03-01 22:18:45.278271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697fca2a3d88'
down_revision = '0c832ede0da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
