"""email

Revision ID: 72ece169657b
Revises: 8d31029266c8
Create Date: 2024-01-29 19:28:17.546797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ece169657b'
down_revision = '8d31029266c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lending', sa.Column('email', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lending', 'email')
    # ### end Alembic commands ###
