"""b

Revision ID: 876d3be3d581
Revises: 4b83ec2277a7
Create Date: 2023-03-08 06:13:33.511903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876d3be3d581'
down_revision = '4b83ec2277a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
