"""store.contact

Revision ID: 8d31029266c8
Revises: 9e706fa6f40f
Create Date: 2023-12-26 20:36:38.911806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d31029266c8'
down_revision = '9e706fa6f40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('email', sa.String(length=500), nullable=True))
    op.add_column('store', sa.Column('telephone', sa.String(length=500), nullable=True))
    op.add_column('store', sa.Column('line', sa.String(length=500), nullable=True))
    op.add_column('store', sa.Column('icon', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'icon')
    op.drop_column('store', 'line')
    op.drop_column('store', 'telephone')
    op.drop_column('store', 'email')
    # ### end Alembic commands ###
