"""entity

Revision ID: 96d0aacb0d69
Revises: 11202f046c60
Create Date: 2023-03-08 00:21:01.016306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d0aacb0d69'
down_revision = '11202f046c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lending', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lending', 'store', ['entity_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lending', type_='foreignkey')
    op.drop_column('lending', 'entity_id')
    # ### end Alembic commands ###
