"""ret

Revision ID: 9e706fa6f40f
Revises: 57857ca85f7f
Create Date: 2023-03-08 07:33:28.576946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e706fa6f40f'
down_revision = '57857ca85f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lending', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lending', 'status')
    # ### end Alembic commands ###
