"""lending

Revision ID: b3222984a151
Revises: c46f9b88f20c
Create Date: 2023-02-04 08:59:33.512422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3222984a151'
down_revision = 'c46f9b88f20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=500), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lending')
    # ### end Alembic commands ###
