"""init

Revision ID: c46f9b88f20c
Revises: 
Create Date: 2023-01-17 19:02:19.693805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c46f9b88f20c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tablename', sa.String(length=500), nullable=True),
    sa.Column('item_id', sa.String(length=500), nullable=True),
    sa.Column('action', sa.String(length=500), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=500), nullable=True),
    sa.Column('passwd', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('admin_store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_store_id'], ['store.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lend_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lend_log')
    op.drop_table('user')
    op.drop_table('entity')
    op.drop_table('store')
    op.drop_table('model_history')
    # ### end Alembic commands ###
