"""lonlat

Revision ID: ca4886dddbf5
Revises: d2f5860e9493
Create Date: 2023-03-01 21:43:57.296646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4886dddbf5'
down_revision = 'd2f5860e9493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('longitude_decimal', sa.Integer(), nullable=True))
    op.add_column('store', sa.Column('latitude_decimal', sa.Integer(), nullable=True))
    op.add_column('store', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'address')
    op.drop_column('store', 'latitude_decimal')
    op.drop_column('store', 'longitude_decimal')
    # ### end Alembic commands ###
