"""entity-status

Revision ID: d2f5860e9493
Revises: b3222984a151
Create Date: 2023-02-04 09:31:26.846587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f5860e9493'
down_revision = 'b3222984a151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'status')
    # ### end Alembic commands ###
